// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Start?"
          text="Your business deserves an online home that converts. Let's talk about your goals today."
          primaryButton={{
            text: "Schedule Consultation",
            href: "wohlanddigital@gmail.com",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "wohlanddigital@gmail.com",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
