// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Questions Answered"
          title="Everything You Need To Know"
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "How long does it take?",
                  answer: "Most projects are completed within 7-14 business days.",
                },
                {
                  question: "Do I need to manage hosting?",
                  answer: "We provide fully managed hosting for all our clients.",
                },
              ],
            },
            {
              name: "Payments",
              items: [
                {
                  question: "Are there hidden costs?",
                  answer: "No. Our quotes are transparent and comprehensive.",
                },
                {
                  question: "Can I pay in installments?",
                  answer: "Yes, we offer flexible payment plans for larger packages.",
                },
              ],
            },
          ]}
          cta={{
            name: "Marcus Wohland",
            role: "Lead Developer",
            buttonText: "Chat with Us",
            buttonHref: "#contact",
            imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-smiley-man-with-laptop_23-2149915909.jpg",
          }}
          textAnimation="slide-up"
          description="Description"
        />
        </SectionErrorBoundary>
      </div>
  );
}
