// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Proven Success"
          title="Our Impact in Numbers"
          description="Results that matter to your business."
          metrics={[
            {
              value: "150+",
              description: "Websites Built",
            },
            {
              value: "200%",
              description: "Average Traffic Increase",
            },
            {
              value: "48hrs",
              description: "Average Response Time",
            },
            {
              value: "99.9%",
              description: "Uptime Guarantee",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
