// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingHighlightedCards from '@/components/sections/pricing/PricingHighlightedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingHighlightedCards
          tag="Transparent Pricing"
          title="Plans for Every Growth Stage"
          description="Clear, upfront pricing with no hidden costs."
          plans={[
            {
              tag: "Starter",
              price: "$1,299",
              description: "Perfect for new local service businesses.",
              features: [
                "Mobile Responsive",
                "5 Pages",
                "Basic SEO",
                "Contact Form",
              ],
              primaryButton: {
                text: "Select Starter",
                href: "#contact",
              },
            },
            {
              tag: "Growth",
              price: "$1,999",
              description: "Ideal for established retail and trade.",
              features: [
                "Advanced SEO",
                "10 Pages",
                "Blog Setup",
                "Booking Integration",
                "Priority Support",
              ],
              highlight: "Best Value",
              primaryButton: {
                text: "Select Growth",
                href: "#contact",
              },
            },
            {
              tag: "Pro",
              price: "$3,999",
              description: "Complete digital presence for teams.",
              features: [
                "Full Ecommerce",
                "Unlimited Pages",
                "Custom Branding",
                "Analytics Dashboard",
                "Monthly Maintenance",
              ],
              primaryButton: {
                text: "Select Pro",
                href: "#contact",
              },
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
