// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product-grid" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductGridSection(): React.JSX.Element {
  return (
    <div id="product-grid" data-section="product-grid">
        <SectionErrorBoundary name="product-grid">
              <FeaturesRevealCardsBento
          tag="Capabilities"
          title="All-in-One Digital Solutions"
          description="We offer comprehensive services to elevate your online presence."
          items={[
            {
              title: "Custom Web Design",
              description: "Unique, high-converting layouts built for your brand identity.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/office-supplies-red-table_171337-13058.jpg",
            },
            {
              title: "Ecommerce Setup",
              description: "Full-featured online stores to scale your sales globally.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/virtual-shopping-experience_23-2151952991.jpg",
            },
            {
              title: "Local SEO",
              description: "Dominate local search results and reach neighborhood customers.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/mobile-app-location-digital-art_23-2151762909.jpg",
            },
            {
              title: "Cloud Hosting",
              description: "High-performance, secure hosting with 99.9% uptime guaranteed.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/security-cloud_1048-2442.jpg",
            },
            {
              title: "Content Strategy",
              description: "Professional copywriting and planning to engage your audience.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/detectives-using-investigation-board_1098-15949.jpg",
            },
            {
              title: "Domain Security",
              description: "SSL certificates and hardened security to protect your data.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/person-working-html-computer_23-2150038843.jpg",
            },
            {
              title: "Ongoing Support",
              description: "Dedicated technical support to keep your site running smoothly.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/standard-quality-control-collage-concept_23-2149595844.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
