// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCards
          tag="How We Help"
          title="Your Business, Online"
          description="We bridge the technical gap so you can focus on your customers."
          items={[
            {
              title: "Rapid Development",
              description: "High-quality, responsive sites delivered in days, not weeks.",
              imageSrc: "http://img.b2bpic.net/free-photo/speed-meter-extreme-scale-fast_53876-120604.jpg",
            },
            {
              title: "SEO Optimized",
              description: "Get found by local customers looking for your services.",
              imageSrc: "http://img.b2bpic.net/free-photo/search-research-subject-terms-vocabulary_53876-120303.jpg",
            },
            {
              title: "Custom Designs",
              description: "Tailored aesthetics that reflect your specific brand values.",
              imageSrc: "http://img.b2bpic.net/free-photo/artistic-color-strokes-isolated_23-2151897722.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
