// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Client Results"
          title="Don't Just Take Our Word"
          description="Helping businesses reach their potential online."
          testimonials={[
            {
              name: "Alex Rivet",
              role: "Local Cafe Owner",
              quote: "Wohland Digital transformed my local reach in weeks.",
              imageSrc: "http://img.b2bpic.net/free-photo/business-woman-working-home_23-2148162643.jpg",
            },
            {
              name: "Jamie Lee",
              role: "Plumbing Expert",
              quote: "Finally found a partner that makes web design simple.",
              imageSrc: "http://img.b2bpic.net/free-photo/freight-parcel-inspiration-uniform-art_1134-1177.jpg",
            },
            {
              name: "Sarah Miller",
              role: "Startup founder",
              quote: "Speed and transparency were top tier. Highly recommend.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-cute-shy-young-asian-woman-standing-front-cafe-entrance-touching-her-neck_1258-199358.jpg",
            },
            {
              name: "David Park",
              role: "Landscaper",
              quote: "My new site paid for itself within two months of launch.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-woman-with-potted-plants_23-2149412615.jpg",
            },
            {
              name: "Elena Ross",
              role: "Boutique Owner",
              quote: "Stunning design and zero technical headaches. Simply great.",
              imageSrc: "http://img.b2bpic.net/free-photo/elderly-man-buys-food-reusable-jars_482257-81582.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
